//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartApp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ProductDescription))]
    
    public partial class Product
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public int ProductDetailId { get; set; }
    	[DataMember]
        public bool IsSold { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StockInDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> SoldDate { get; set; }
    
    	[DataMember]
        public virtual ProductDescription ProductDescription { get; set; }
    }
}
