//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public ProductDescription()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription1 { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Customer { get; set; }
        public decimal Price { get; set; }
    
        public virtual Brand Brand1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Color Color1 { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual Size Size1 { get; set; }
    }
}
