//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ProductDescriptions = new HashSet<ProductDescription>();
        }
    
        public int Id { get; set; }
        public decimal SizeNumber { get; set; }
        public string SizeDescription { get; set; }
    
        public virtual ICollection<ProductDescription> ProductDescriptions { get; set; }
    }
}
